# Makefile for driver

TARGET_NAME:=cpq_gpio

SRC_DIR:=src/drivers/$(TARGET_NAME)

SRCS:= $(TARGET_NAME).c

LINKS := dev/misc/$(TARGET_NAME)

MY_INCLUDES :=

SYSTEM_LIBS :=

MY_CFLAGS :=


include $(SDIR_TEMPLATES)/DriverTemplate.mk
