# usb/raw Driver Makefile
# Copyright (c) 2000; Be, Inc. All Rights Reserved.

TARGET_NAME:=kodak_usb

SRC_DIR:=src/drivers/usb/kodak

SRCS	:= $(TARGET_NAME).c

LINKS := dev/camera/usb/$(TARGET_NAME)

MY_INCLUDES := 

SYSTEM_LIBS :=

MY_CFLAGS := 

include $(SDIR_TEMPLATES)/DriverTemplate.mk
