
include $(BUILDHOME)/src/drivers/pcmcia/ds/$(MAKEFILE_LEAFNAME)
include $(BUILDHOME)/src/drivers/pcmcia/dummy/$(MAKEFILE_LEAFNAME)
include $(BUILDHOME)/src/drivers/pcmcia/memory/$(MAKEFILE_LEAFNAME)
include $(BUILDHOME)/src/drivers/pcmcia/serial/$(MAKEFILE_LEAFNAME)
