# Makefile for driver

TARGET_NAME:=pkgig

SRC_DIR:=src/drivers/hamachi

SRCS		:= hamachi.c \
				area.c \
				memio.c \
#

LINKS := dev/net/hamachi

MY_INCLUDES := -I$(BUILDHOME)/src/inc/driver

SYSTEM_LIBS :=

MY_CFLAGS := 

include $(SDIR_TEMPLATES)/DriverTemplate.mk


