
// This is the main export that the fsil uses to find the functions.
#include "export.h"

int32	api_version = B_CUR_FS_API_VERSION;

vnode_ops fs_entry = {

&ntfs_read_vnode,
&ntfs_write_vnode,
NULL, //&ntfs_remove_vnode,
NULL, //&ntfs_secure_vnode,
&ntfs_walk,
&ntfs_access,
NULL, //&ntfs_create,
NULL, //&ntfs_mkdir,
NULL, //&ntfs_symlink,
NULL, //&ntfs_link,
NULL, //&ntfs_rename,
NULL, //&ntfs_unlink,
NULL, //&ntfs_rmdir,
NULL, //&ntfs_readlink,
&ntfs_opendir,
&ntfs_closedir,
&ntfs_free_dircookie,
&ntfs_rewinddir,
&ntfs_readdir,
&ntfs_open,
&ntfs_close,
&ntfs_free_cookie,
&ntfs_read,
NULL, //&ntfs_write,
NULL, //&ntfs_readv,
NULL, //&ntfs_writev,
&ntfs_ioctl,
NULL, //&ntfs_setflags,
&ntfs_rstat,
NULL, //&ntfs_wstat,
NULL, //&ntfs_fsync,
NULL, //&ntfs_initialize,
&ntfs_mount,
&ntfs_unmount,
NULL, //&ntfs_sync,
&ntfs_rfsstat,
NULL, //&ntfs_wfsstat,
NULL, // select
NULL, // deselect
NULL, //&ntfs_open_indexdir,
NULL, //&ntfs_close_indexdir,
NULL, //&ntfs_free_indexdircookie,
NULL, //&ntfs_rewind_indexdir,
NULL, //&ntfs_read_indexdir,
NULL, //&ntfs_create_index,
NULL, //&ntfs_remove_index,
NULL, //&ntfs_rename_index,
NULL, //&ntfs_stat_index,
&ntfs_open_attrdir,
&ntfs_close_attrdir,
&ntfs_free_attrdircookie,
&ntfs_rewind_attrdir,
&ntfs_read_attrdir,
NULL, //&ntfs_write_attr,
&ntfs_read_attr,
NULL, //&ntfs_remove_attr,
NULL, //&ntfs_rename_attr,
&ntfs_stat_attr,
NULL, //&ntfs_open_query,
NULL, //&ntfs_close_query,
NULL, //&ntfs_free_querycookie,
NULL, //&ntfs_read_query
};
