//****************************************************************************
//
// DELAY.H - Prototypes for the functions in delay.cpp.
//
// Copyright (c) 1997-1998 Crystal Semiconductor Corp.
//
//****************************************************************************

#ifndef _H_DELAY_SUPPORT
#define _H_DELAY_SUPPORT

 void delay(unsigned long ulNumMicroSecs);

#endif // _H_DELAY_SUPPORT
