# Makefile for driver

TARGET_NAME:=lcd

SRC_DIR:=src/drivers/ns9210

SRCS:= $(TARGET_NAME).c

LINKS := dev/misc/$(TARGET_NAME)

MY_INCLUDES := -I$(PRIVATE_INCLUDE_PATH)/driver

SYSTEM_LIBS :=

MY_CFLAGS :=


include $(SDIR_TEMPLATES)/DriverTemplate.mk


