
SRC_DIR:=src/drivers/pctel/pctel.libs
SOURCE:=control.a
TARGET:= $(BELIBRARIES)/pctel_control.a
PERMISSIONS:=$(PERMS_SYSTEM_DATA)
include $(SDIR_TEMPLATES)/HostDataFileTemplate.mk

SRC_DIR:=src/drivers/pctel/pctel.libs
SOURCE:=dsp.a
TARGET:= $(BELIBRARIES)/pctel_dsp.a
PERMISSIONS:=$(PERMS_SYSTEM_DATA)
include $(SDIR_TEMPLATES)/HostDataFileTemplate.mk

