# Makefile for driver

TARGET_NAME:=ramdisk

SRC_DIR:=src/drivers/$(TARGET_NAME)

SRCS:= $(TARGET_NAME).c

LINKS := dev/disk/virtual/$(TARGET_NAME)

MY_INCLUDES := 

SYSTEM_LIBS :=

MY_CFLAGS :=


include $(SDIR_TEMPLATES)/DriverTemplate.mk
