# usb/printer Driver Makefile
# Copyright (c) 2000; Be, Inc. All Rights Reserved.

TARGET_NAME:=gempc430

SRC_DIR:=src/drivers/usb/gempc430_iad

SRCS	:= gempc430.c

LINKS := dev/printer/usb/$(TARGET_NAME)

MY_INCLUDES := -I$(PRIVATE_INCLUDE_PATH)/usb_p

SYSTEM_LIBS :=

MY_CFLAGS := 

LINKS := dev/smartcard/usb/gempc430/$(TARGET_NAME)


include $(SDIR_TEMPLATES)/DriverTemplate.mk
