 4 mod} if} if /Orientation exch def 
currentdict end setpagedevice"
*End
*PageSize A4: "[595 842] 1 2 dict begin exch /PageSize exch def version cvr 2015 
lt {PageSize aload pop gt {3 add 4 mod} if} if /Orientation exch def currentdict 
end setpagedevice"
*End
*PageSize A4.Transverse: "[595 842] 0 2 dict begin exch /PageSize exch def 
version cvr 2015 lt {PageSize aload pop gt {3 add 4 mod} if} if /Orientation 
exch def currentdict end setpagedevice"
*End
*PageSize A4Extra: "[667 914] 1 2 dict begin exch /PageSize exch def version cvr 
2015 lt {PageSize aload pop gt {3 add 4 mod} if} if /Orientation exch def 
currentdict end setpagedevice"
*End
*PageSize A4Extra.Transverse: "[667 914] 0 2 dict begin exch /PageSize exch def 
version cvr 2015 lt {PageSize aload pop gt {3 add 4 mod} 