# Makefile for driver
#
# DON'T BE FOOLED! This is the old tty driver.
#

TARGET_NAME:=tty

SRC_DIR:=src/drivers/$(TARGET_NAME)

SRCS:= $(TARGET_NAME).c

MY_INCLUDES :=

SYSTEM_LIBS:=

MY_CFLAGS :=

INSTALL_PREFIX :=
INSTALL_TARGET :=


include $(SDIR_TEMPLATES)/KernelAddonTemplate.mk
