DTH="161" BACKGROUND="../../images/side_cat.gif">
									<FONT COLOR="C5C5A6">...</FONT><A HREF="../games/index.html">Games</A>
								</TD>
							</TR>
							<TR>
								<TD HEIGHT="20" WIDTH="161" BACKGROUND="../../images/side_cat.gif">
									<FONT COLOR="C5C5A6">...</FONT><A HREF="../ps2/index.html">Sony PS2</A>
								</TD>
							</TR>
							<TR>
								<TD HEIGHT="20" WIDTH="161" BACKGROUND="../../images/side_cat.gif">
									<FONT COLOR="C5C5A6">...</FONT><A HREF="../gameshow/index.html">Game Show Network</A>
								</TD>
							</TR>
							<TR>
								<TD HEIGHT="20" WIDTH="161" BACKGROUND="../../images/side_cat.gif">
									<FONT COLOR="C5C5A6">...</FONT><A HREF="../station/index.html">The Station</A>
								</TD>
							</TR>
							<TR>
								<TD HEIGHT="12" WIDTH="161" BACKGROUND="../../images/side_cat_bot.gif">
								</TD>
							</TR>
						</TABLE>
					</TD>
				</TR>
			</TABLE>
		</TD>
		<TD VALIGN="top" ALIGN="left" COLSPAN="2">
			<TABLE WIDTH=625 BORDER=0 CELLPADDING=0 CELLSPACING=0>
				<TR>
					<TD>
						<IMG SRC="../../images/netguide.gif" WIDTH=55 HEIGHT=32></TD>
					<TD>
						<A HREF="../../news/index.html" OnMouseOver="document.news.src='../../images/r_news.gif'" OnMouseOut="document.news.