# Driver Makefile
# Copyright (c) 2000-2001; Be, Inc. All Rights Reserved.

TARGET_NAME:=mo

SRC_DIR:=src/drivers/usb/vdsp

SRCS	:= vdsp.c

LINKS := dev/midi/$(TARGET_NAME)

MY_INCLUDES := -I$(BUILDHOME)/src/inc/usb_p

SYSTEM_LIBS :=

MY_CFLAGS := 


include $(SDIR_TEMPLATES)/DriverTemplate.mk
