enter" width="25%"><a href="#To Configure a Transition"><small>Configure
        a Transition</small></a></td>
      </tr>
    </table>
    </div><p>To liven up your presentations, you can set each slide to have a transition
    effect. &nbsp; When the slide is displayed, rather than merely popping up on the screen,
    the slide contents can be unveiled using a few different animation effects. </p>
    <h2><a name="Transition Types">Transition Types</a></h2>
    <p>Gobe Productive presentations includes the following transition types. </p>
    <blockquote>
      <p><strong>Jump</strong>:&nbsp; This is the standard slide transition.&nbsp; There are no
      effects, the slide just appears all at once. </p>
      <p><strong>Wipe</strong>:&nbsp; The slide is wiped off the screen and replaced with the
      next slide. </p>
      <p><strong>Venetian Blinds</strong>:&nbsp; The slide is cut up into sections and each
      section &quot;flips&quot; to