" BORDER="0"></TD>
					<TD>
						<A HREF="../../shopping/index.html" OnMouseOver="document.shopping.src='../../images/r_shopping.gif'" OnMouseOut="document.shopping.src='../../images/h_shopping.gif'"><IMG SRC="../../images/h_shopping.gif" WIDTH=88 HEIGHT=32 NAME="shopping" BORDER="0"></A></TD>
					<TD>
						<A HREF="../../lifestyle/index.html" OnMouseOv